name: Build HqErotico

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/pt/hqerotico/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Format Code
        run: ./gradlew :src:pt:hqerotico:spotlessApply

      - name: Build Extension
        run: ./gradlew :src:pt:hqerotico:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hqerotico-apk
          path: src/pt/hqerotico/build/outputs/apk/release/*.apk
